export const ASK_Q = "ASK_Q";

export const SET_ERRORS = "SET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_Q = "FETCH_Q";
export const FETCH_ANSWERS = "FETCH_ANSWERS";

export const QUESTION_FILTER = "QUESTION_FILTER";

export const DELETE_QUESTION = "DELETE_QUESTION";

export const FILTER_QUESTION_BY_Major = "FILTER_QUESTION_BY_Major";

export const RESET = "RESET";

export const FILTER_QUESTION_BY_ANSWER = "FILTER_QUESTION_BY_ANSWER";

export const FILTER_QUESTION_BY_APPROVE = "FILTER_QUESTION_BY_APPROVE";

export const FETCH_QUESTION_DETAIL = "FETCH_QUESTION_DETAIL";

export const SEND_ANSWERS = "SEND_ANSWERS";

export const FETCH_MAJORS = "FETCH_MAJORS";
